---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec: 
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels:
      name: bggapp-pod
      version: v1
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
        version: v1
    spec:          
      containers: 
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggapp-pod-port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-config
        - secretRef:
            name: bgg-secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          failureThreshold: 3
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec: 
  type: LoadBalancer
  selector: 
    name: bggapp-pod
    version: v1
  ports:
  - name: bggapp-svc-port
    port: 80
    targetPort: bggapp-pod-port